[project]
authors = ["Anshul Singhvi <asinghvi17@simons-rock.edu>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "raster-benchmark"
platforms = ["osx-64"]
version = "0.1.0"

[tasks]
benchmarks = { cmd = "run_benchmarks.sh", description = "Run benchmarks across languages" }

[dependencies]
r = ">=4.3,<5"
python = ">=3.11.6,<4"
xarray = ">=2024.9.0,<2025"
rioxarray = ">=0.17.0,<0.18"
r-exactextractr = ">=0.9.1,<0.10"
r-raster = ">=3.6_26,<4"
r-stars = ">=0.6_6,<0.7"
r-terra = ">=1.7_39,<2"
rasterio = ">=1.3.7,<2"
rasterstats = ">=0.19.0,<0.20"
fiona = ">=1.9.4,<2"
pandas = ">=2.2.3,<3"
geopandas = ">=0.14.4,<0.15"
pygeos = ">=0.14,<0.15"
julia = ">=1.9.3,<2"
r-tibble = ">=3.2.1,<4"
r-sf = ">=1.0_15,<2" # stars needs sf >= 1.0_15
r-s2 = ">=1.1.4,<2"
